# Generated by Django 2.0.5 on 2018-05-26 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_artcilesource_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artcilesource',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.InstagramAccount'),
        ),
    ]
