# Generated by Django 2.0.5 on 2018-05-27 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_artcilesource_cached_properties'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('url', models.URLField(max_length=500)),
                ('file', models.FileField(null=True, upload_to='')),
                ('res', models.IntegerField(null=True)),
                ('width', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('offset_x', models.IntegerField(null=True)),
                ('thumbnail_file', models.FileField(null=True, upload_to='')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.ArtcileSource')),
            ],
        ),
    ]
