# Generated by Django 2.0.5 on 2018-05-27 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0005_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ArticleImage',
        ),
    ]
